//! Bounded control-layout probe for direct-coordinate G32 tables.
//!
//! Compare the existing range-pruned bit trie with an explicit equality branch
//! for its final power-of-two leaf. The remaining table is complete and needs
//! one fewer selector bit. This changes only selection control: each leaf emits
//! the same 25 trusted coordinate limbs, with zero witness hints and one selector
//! data item per invocation. All 48 selections in the G32 leaf add zero hint
//! items; the complete verifier still starts with 803 witness/data items.
//!
//! The table-only strict checks preserve 948 main-stack plus two altstack
//! sentinel items to audit composition against the combined 1,000-item limit.
//! Multi-megabyte generation is excluded.

#[allow(dead_code)]
#[path = "ed25519_fixed_table_actual_model.rs"]
mod table_model;

use bitcoin_lab::support::{
    execution::execute_raw_script_with_inputs_strict,
    script::{script, Script, ScriptCompilation, MAX_OPTIMIZER_INPUT_BYTES},
};

fn selector_bits(width: usize, streamed: bool) -> Script {
    script! {
        for bit in (0..width).rev() {
            OP_DUP { (1u32 << bit) - 1 } OP_GREATERTHAN
            if streamed {
                OP_DUP OP_TOALTSTACK
                OP_IF { 1u32 << bit } OP_SUB OP_ENDIF
            } else {
                OP_SWAP OP_OVER
                OP_IF { 1u32 << bit } OP_SUB OP_ENDIF
            }
        }
        OP_NOT OP_VERIFY
        if streamed {
            for _ in 0..width { OP_FROMALTSTACK }
        } else {
            for depth in 1..width { { depth as u32 } OP_ROLL }
        }
    }
}

fn leaf(values: &[i32; 25]) -> Script {
    script! { for value in values { { *value } } }
}

fn trie(entries: &[[i32; 25]], indices: &[usize], remaining: usize) -> Script {
    if remaining == 0 {
        assert_eq!(indices.len(), 1);
        return leaf(&entries[indices[0]]);
    }
    let bit = remaining - 1;
    let (ones, zeros): (Vec<_>, Vec<_>) = indices
        .iter()
        .copied()
        .partition(|index| index & (1 << bit) != 0);
    match (zeros.is_empty(), ones.is_empty()) {
        (false, false) => script! {
            OP_IF { trie(entries, &ones, bit) }
            OP_ELSE { trie(entries, &zeros, bit) } OP_ENDIF
        },
        (false, true) => script! { OP_NOT OP_VERIFY { trie(entries, &zeros, bit) } },
        (true, false) => script! { OP_VERIFY { trie(entries, &ones, bit) } },
        _ => unreachable!(),
    }
}

fn table(entries: &[[i32; 25]], width: usize, boundary: bool, streamed: bool) -> Script {
    let indices = (0..entries.len()).collect::<Vec<_>>();
    if boundary {
        let maximum = entries.len() - 1;
        assert_eq!(maximum, 1 << (width - 1));
        script! {
            OP_DUP { maximum as u32 } OP_NUMEQUAL
            OP_IF OP_DROP { leaf(&entries[maximum]) }
            OP_ELSE
                { selector_bits(width - 1, streamed) }
                { trie(entries, &indices[..maximum], width - 1) }
            OP_ENDIF
        }
    } else {
        script! {
            { selector_bits(width, streamed) }
            { trie(entries, &indices, width) }
        }
    }
}

fn item(value: i64) -> Vec<u8> {
    let mut bytes = [0u8; 8];
    let length = bitcoin::script::write_scriptint(&mut bytes, value);
    bytes[..length].to_vec()
}

fn executable_with_raw_policy(table: Script) -> bitcoin::ScriptBuf {
    // Preserve the larger leaf's NONE compilation behavior without manually
    // bypassing centralized policy. Padding is unreachable and excluded from
    // table metrics; strict execution still parses every byte.
    let copies = MAX_OPTIMIZER_INPUT_BYTES / table.len() + 1;
    script! {
        { table.clone() }
        OP_0 OP_IF for _ in 0..copies { { table.clone() } } OP_ENDIF
        OP_1
    }
    .compile_with_policy()
}

fn raw_static_ops(table: Script) -> usize {
    let copies = MAX_OPTIMIZER_INPUT_BYTES / table.len() + 1;
    let count = executable_with_raw_policy(table)
        .instructions()
        .map(|item| item.expect("generated bytecode parses"))
        .filter(|item| matches!(item, bitcoin::script::Instruction::Op(op) if op.to_u8() > 0x60))
        .count();
    assert_eq!((count - 2) % (copies + 1), 0);
    (count - 2) / (copies + 1)
}

fn main() {
    let started = std::time::Instant::now();
    let tables = table_model::montgomery_direct_h16_qfree_g32_host_tables();
    let widths = table_model::montgomery_direct_h16_qfree_g32_response_widths();
    if std::env::args().any(|arg| arg == "--leaf-policy") {
        let mut raw = 0usize;
        let mut optimized = 0usize;
        for entries in tables
            .response_low_to_high
            .iter()
            .chain(&tables.challenge_low_to_high)
        {
            for values in entries {
                let fragment = leaf(values);
                raw += fragment.len();
                optimized += fragment.compile_with_policy().len();
            }
        }
        println!("leaf_raw_bytes={raw}");
        println!("leaf_small_policy_bytes={optimized}");
        println!("leaf_policy_saving={}", raw - optimized);
        println!("elapsed_ms={}", started.elapsed().as_millis());
        return;
    }
    let mut old_total = 0usize;
    let mut boundary_total = 0usize;
    let mut streamed_total = 0usize;
    let mut static_ops_saving = 0usize;
    let mut sample = None;
    for (entries, width) in tables.response_low_to_high.iter().zip(widths).chain(
        tables
            .challenge_low_to_high
            .iter()
            .map(|entries| (entries, 8)),
    ) {
        assert_eq!(entries.len(), (1 << (width - 1)) + 1);
        let old = table(entries, width, false, false);
        let boundary = table(entries, width, true, false);
        let streamed = table(entries, width, true, true);
        old_total += old.len();
        boundary_total += boundary.len();
        streamed_total += streamed.len();
        static_ops_saving += raw_static_ops(old.clone()) - raw_static_ops(streamed.clone());
        if sample.is_none() && entries.len() == 129 {
            sample = Some((entries.clone(), old, boundary, streamed));
        }
    }
    assert_eq!(old_total, 583_847);
    println!("baseline_table_bytes={old_total}");
    println!("boundary_table_bytes={boundary_total}");
    println!("boundary_saving={}", old_total - boundary_total);
    println!("boundary_streamed_table_bytes={streamed_total}");
    println!("boundary_streamed_saving={}", old_total - streamed_total);
    println!("boundary_streamed_static_op_saving={static_ops_saving}");
    let production = table_model::montgomery_direct_h16_qfree_g32_table_fragments();
    let production_response_bytes = production
        .response_low_to_high
        .iter()
        .map(Script::len)
        .sum::<usize>();
    let production_challenge_bytes = production
        .challenge_low_to_high
        .iter()
        .map(Script::len)
        .sum::<usize>();
    assert_eq!(
        production_response_bytes + production_challenge_bytes,
        streamed_total
    );
    for ((entries, width), fragment) in tables
        .response_low_to_high
        .iter()
        .zip(table_model::montgomery_direct_h16_qfree_g32_response_widths())
        .zip(&production.response_low_to_high)
    {
        assert_eq!(
            executable_with_raw_policy(table(entries, width, true, true)),
            executable_with_raw_policy(fragment.clone())
        );
    }
    for (entries, fragment) in tables
        .challenge_low_to_high
        .iter()
        .zip(&production.challenge_low_to_high)
    {
        assert_eq!(
            executable_with_raw_policy(table(entries, 8, true, true)),
            executable_with_raw_policy(fragment.clone())
        );
    }
    println!("production_response_table_bytes={production_response_bytes}");
    println!("production_challenge_table_bytes={production_challenge_bytes}");
    println!("hint_items_per_invocation=0");
    println!("hint_items_for_48_tables=0");
    println!("complete_selector_data_items_per_invocation=1");
    println!("whole_verifier_entry_items=803");
    let (entries, old, boundary, streamed) = sample.expect("width8 table exists");
    for (label, fragment) in [("old", old), ("boundary", boundary), ("streamed", streamed)] {
        let guarded = script! {
            OP_11 OP_TOALTSTACK OP_13 OP_TOALTSTACK
            { fragment }
            OP_FROMALTSTACK OP_13 OP_EQUALVERIFY
            OP_FROMALTSTACK OP_11 OP_EQUALVERIFY
        };
        let executable = executable_with_raw_policy(guarded);
        assert!(executable.len() > MAX_OPTIMIZER_INPUT_BYTES);
        let mut peak = 0usize;
        for selector in 0..entries.len() {
            let mut inputs = vec![item(7); 948];
            inputs.push(item(selector as i64));
            let result = execute_raw_script_with_inputs_strict(executable.to_bytes(), inputs);
            assert!(result.error.is_none(), "{label}/{selector}: {result}");
            let mut expected = vec![item(7); 948];
            expected.extend(entries[selector].iter().map(|x| item(i64::from(*x))));
            expected.push(item(1));
            assert_eq!(result.final_stack.len(), expected.len());
            for (index, value) in expected.iter().enumerate() {
                assert_eq!(
                    result.final_stack.get(index),
                    *value,
                    "{label}/{selector}/{index}"
                );
            }
            peak = peak.max(result.stats.max_nb_stack_items as usize);
        }
        for invalid in [-1i64, 129, 255, 256, i64::from(i32::MAX)] {
            let result =
                execute_raw_script_with_inputs_strict(executable.to_bytes(), vec![item(invalid)]);
            assert!(result.error.is_some(), "{label} accepted {invalid}");
        }
        println!("{label}_combined_peak_with_950_preserved={peak}");
    }
    println!("compilation=unoptimized_NONE_above_cutoff");
    println!("evidence=locally-reproduced");
    println!("execution_class=unclassified");
    println!("evidence_boundary=selected_table_fragments_in_strict_local_tapscript");
    println!("elapsed_ms={}", started.elapsed().as_millis());
}
