//! Generation-only linker for the zero-hint, trace-only Montgomery H16 leaf.
//!
//! This is deliberately separate from `ed25519_montgomery_h16_full_linker`.
//! The older linker remains the comparison point for the centered challenge
//! and witness-supplied quotient construction.
//!
//! Exact entry, bottom-to-top, is
//! `challenge_trace[16] | response_trace[28] | scalar_words[8]`: 712 hostile
//! data items and exactly zero auxiliary hint items.  After the response
//! schedule, the remaining stack is the 256-item challenge trace followed by
//! the 41-item current state.  The BLAKE3 boundary deep-copies the eight packed
//! Rtilde words from the untouched bottom challenge packet at word-zero depth
//! 289, hashes that copy, and preserves all 297 original items byte-for-byte.
//! The last derived challenge transition later certifies and consumes those
//! same original words, so a retained R copy and endpoint equality check would
//! be redundant.
//!
//! Default execution only checks constants and reports the composition plan.
//! `--measure-bytes` explicitly opts into multi-megabyte generation, but still
//! does not execute the leaf.

#[allow(dead_code)]
#[path = "ed25519_fixed_table_actual_model.rs"]
mod table_model;

#[allow(dead_code)]
#[path = "ed25519_h16_midpoint_glue.rs"]
mod midpoint;

#[allow(dead_code)]
#[path = "ed25519_montgomery_h16_qfree_scheduler.rs"]
mod qfree_scheduler;

use bitcoin::{script::Instruction, ScriptBuf};
use bitcoin_lab::{
    hashes::blake3::ed25519_challenge,
    support::script::{script, Script, ScriptCompilation, MAX_OPTIMIZER_INPUT_BYTES},
};

const RESPONSE_GROUPS: usize = 29;
const CHALLENGE_GROUPS: usize = 16;
const FINAL_STATE_ITEMS: usize = 41;
const TRACE_ITEMS: usize = (RESPONSE_GROUPS - 1 + CHALLENGE_GROUPS) * 16;
const SCALAR_ITEMS: usize = 8;
const AUXILIARY_HINT_ITEMS: usize = 0;

// Independently generated by the bounded q-free scheduler accounting mode.
// The linker asserts the corresponding additive boundaries without executing
// any transition or whole leaf.
const EXPECTED_TABLE_BYTES: usize = 826_072;
const EXPECTED_SCALAR_VALIDATOR_RAW_BYTES: usize = 791;
const EXPECTED_SCALAR_VALIDATOR_POLICY_BYTES: usize = 774;
const EXPECTED_RESPONSE_SCAFFOLD_RAW_BYTES: usize = 13_681;
const EXPECTED_CHALLENGE_SCAFFOLD_RAW_BYTES: usize = 5_451;
const EXPECTED_FIRST_DERIVED_KERNEL_BYTES: usize = 45_455;
const EXPECTED_RESPONSE_CHAINED_KERNEL_BYTES: usize = 1_843_965;
const EXPECTED_CHALLENGE_CHAINED_KERNEL_BYTES: usize = 1_092_720;
const EXPECTED_DERIVED_KERNEL_BYTES: usize = 2_982_140;
const EXPECTED_QFREE_NON_TABLE_RAW_BYTES: usize = 3_002_063;
const ANALYTICAL_DERIVED_COMBINED_STACK_PEAK: usize = 912;
const STRICT_SYNTHETIC_ROUTING_PEAK: usize = 763;
const EXPECTED_PACKED_R_DIRECT_HASH_POLICY_BYTES: usize = 63_830;
const EXPECTED_PACKED_R_CONVERSION_POLICY_BYTES: usize = 3_976;
const EXPECTED_PACKED_R_HASH_BYTES: usize =
    EXPECTED_PACKED_R_DIRECT_HASH_POLICY_BYTES + EXPECTED_PACKED_R_CONVERSION_POLICY_BYTES;
const EXPECTED_INDEPENDENT_RECODER_POLICY_BYTES: usize = 389;
const EXPECTED_TERMINAL_POLICY_BYTES: usize = 22;
// Exact sum of focused policy-produced components. The whole leaf remains a
// projection until `--measure-bytes` explicitly regenerates its serialization.
const ADDITIVE_PROJECTED_LINKED_SCRIPT_BYTES: usize = 3_896_335;

const FIXTURE_PUBLIC_KEY: [u8; 32] = [
    0x7d, 0xb0, 0xdc, 0x92, 0x22, 0xf3, 0xc1, 0x83, 0x45, 0x7d, 0xdd, 0xe4, 0xc7, 0x08, 0xde, 0x8e,
    0x5e, 0xa6, 0xbf, 0x3d, 0x5c, 0x44, 0x04, 0xcc, 0xa1, 0x4b, 0x32, 0x72, 0x9a, 0x05, 0xc3, 0x2a,
];

fn challenge_domain() -> [u8; 32] {
    *blake3::hash(b"bitcoin-lab/custom-ed25519-blake3-slope-v1").as_bytes()
}

fn fixed_message() -> [u8; 32] {
    std::array::from_fn(|index| (index as u8).wrapping_mul(7))
}

fn policy_precompile(name: &'static str, fragment: Script) -> Script {
    Script::new(name).push_script(fragment.compile_with_policy())
}

/// The final derived transition has already authenticated every remaining
/// state item.  The complete leaf needs only discard that fragment result and
/// leave one clean truthy item.
fn terminal_cleanstack_predicate() -> Script {
    script! {
        for _ in 0..FINAL_STATE_ITEMS / 2 { OP_2DROP }
        if FINAL_STATE_ITEMS % 2 != 0 { OP_DROP }
        OP_1
    }
}

fn static_non_push_opcodes(script: &ScriptBuf) -> usize {
    script
        .instructions()
        .map(|instruction| instruction.expect("generated script must parse"))
        .filter(
            |instruction| matches!(instruction, Instruction::Op(opcode) if opcode.to_u8() > 0x60),
        )
        .count()
}

struct LinkedLeaf {
    whole: Script,
    table_bytes: usize,
    scalar_validator_bytes: usize,
    response_bytes: usize,
    hash_bytes: usize,
    recoder_bytes: usize,
    challenge_bytes: usize,
    terminal_bytes: usize,
}

/// Assemble the real zero-hint candidate without executing it.
///
/// This function is intentionally called only by the explicit measurement
/// mode: table and derived-kernel materialization produces a multi-megabyte
/// Script.  All small standalone fragments are policy-precompiled before they
/// are embedded because the final leaf necessarily takes the policy's
/// `CompileOptions::NONE` path.
fn build_linked_leaf() -> LinkedLeaf {
    let table_model::MontgomeryDirectH16TableFragments {
        response_low_to_high,
        challenge_low_to_high,
        public_key_compressed,
    } = table_model::montgomery_direct_h16_independent_byte_table_fragments();
    assert_eq!(public_key_compressed, FIXTURE_PUBLIC_KEY);

    let table_bytes: usize = response_low_to_high
        .iter()
        .chain(&challenge_low_to_high)
        .map(Script::len)
        .sum();
    assert_eq!(table_bytes, EXPECTED_TABLE_BYTES);

    let scalar_validator_raw = qfree_scheduler::qfree_scalar_validator();
    assert_eq!(
        scalar_validator_raw.len(),
        EXPECTED_SCALAR_VALIDATOR_RAW_BYTES
    );
    let scalar_validator = policy_precompile(
        "policy-precompiled q-free scalar validator",
        scalar_validator_raw,
    );
    let response = qfree_scheduler::build_qfree_response_stream(response_low_to_high);

    // Do not call the scheduler's standalone R-copy probe here.  This helper
    // performs the one required deep copy from the preserved challenge packet.
    let hash =
        ed25519_challenge::key_specialized_compute_script_preserving_truncated_128_fixed_message_from_certified_packed_r(
            challenge_domain(),
            public_key_compressed,
            fixed_message(),
            qfree_scheduler::QFREE_HASH_PRESERVED_ITEMS as u32,
            qfree_scheduler::QFREE_HASH_R_WORD0_DEPTH as u32,
        );
    let recoder = policy_precompile(
        "policy-precompiled independent-byte challenge recoder",
        midpoint::recode_blake3_low128_independent_byte127(
            qfree_scheduler::QFREE_HASH_PRESERVED_ITEMS,
        ),
    );
    let challenge = qfree_scheduler::build_qfree_challenge_schedule(challenge_low_to_high);
    let terminal = policy_precompile(
        "policy-precompiled q-free cleanstack predicate",
        terminal_cleanstack_predicate(),
    );

    let scalar_validator_bytes = scalar_validator.len();
    let response_bytes = response.len();
    let hash_bytes = hash.len();
    let recoder_bytes = recoder.len();
    let challenge_bytes = challenge.len();
    let terminal_bytes = terminal.len();
    assert_eq!(
        scalar_validator_bytes,
        EXPECTED_SCALAR_VALIDATOR_POLICY_BYTES
    );
    assert_eq!(
        response_bytes + challenge_bytes,
        EXPECTED_TABLE_BYTES
            + EXPECTED_RESPONSE_SCAFFOLD_RAW_BYTES
            + EXPECTED_CHALLENGE_SCAFFOLD_RAW_BYTES
            + EXPECTED_DERIVED_KERNEL_BYTES
    );
    assert_eq!(
        EXPECTED_FIRST_DERIVED_KERNEL_BYTES
            + EXPECTED_RESPONSE_CHAINED_KERNEL_BYTES
            + EXPECTED_CHALLENGE_CHAINED_KERNEL_BYTES,
        EXPECTED_DERIVED_KERNEL_BYTES
    );
    assert_eq!(
        EXPECTED_SCALAR_VALIDATOR_RAW_BYTES
            + EXPECTED_RESPONSE_SCAFFOLD_RAW_BYTES
            + EXPECTED_CHALLENGE_SCAFFOLD_RAW_BYTES
            + EXPECTED_DERIVED_KERNEL_BYTES,
        EXPECTED_QFREE_NON_TABLE_RAW_BYTES
    );
    assert_eq!(hash_bytes, EXPECTED_PACKED_R_HASH_BYTES);
    assert_eq!(recoder_bytes, EXPECTED_INDEPENDENT_RECODER_POLICY_BYTES);
    assert_eq!(terminal_bytes, EXPECTED_TERMINAL_POLICY_BYTES);
    let whole = script! {
        { scalar_validator }
        { response }
        { hash }
        { recoder }
        { challenge }
        { terminal }
    };

    LinkedLeaf {
        whole,
        table_bytes,
        scalar_validator_bytes,
        response_bytes,
        hash_bytes,
        recoder_bytes,
        challenge_bytes,
        terminal_bytes,
    }
}

fn check_shape() {
    assert_eq!(
        ADDITIVE_PROJECTED_LINKED_SCRIPT_BYTES,
        EXPECTED_SCALAR_VALIDATOR_POLICY_BYTES
            + EXPECTED_TABLE_BYTES
            + EXPECTED_RESPONSE_SCAFFOLD_RAW_BYTES
            + EXPECTED_CHALLENGE_SCAFFOLD_RAW_BYTES
            + EXPECTED_DERIVED_KERNEL_BYTES
            + EXPECTED_PACKED_R_HASH_BYTES
            + EXPECTED_INDEPENDENT_RECODER_POLICY_BYTES
            + EXPECTED_TERMINAL_POLICY_BYTES
    );
    assert_eq!(TRACE_ITEMS, 704);
    assert_eq!(qfree_scheduler::QFREE_ENTRY_ITEMS, 712);
    assert_eq!(
        qfree_scheduler::QFREE_ENTRY_ITEMS,
        TRACE_ITEMS + SCALAR_ITEMS
    );
    assert_eq!(qfree_scheduler::QFREE_HASH_PRESERVED_ITEMS, 297);
    assert_eq!(qfree_scheduler::QFREE_HASH_R_WORD0_DEPTH, 289);
    assert!(
        qfree_scheduler::QFREE_HASH_R_WORD0_DEPTH + 8
            <= qfree_scheduler::QFREE_HASH_PRESERVED_ITEMS
    );

    println!("model=ed25519_montgomery_h16_qfree_full_linker");
    println!("mode=shape-only");
    println!("multi_megabyte_generation_performed=false");
    println!("whole_leaf_execution_performed=false");
    println!("entry_layout=challenge16_trace|response28_trace|scalar8");
    println!("trace_data_items={TRACE_ITEMS}");
    println!("scalar_data_items={SCALAR_ITEMS}");
    println!("auxiliary_hint_items={AUXILIARY_HINT_ITEMS}");
    println!(
        "complete_argument_items_at_script_entry={}",
        qfree_scheduler::QFREE_ENTRY_ITEMS
    );
    println!("all_entry_items_coexist=true");
    println!(
        "post_response_preserved_items={}",
        qfree_scheduler::QFREE_HASH_PRESERVED_ITEMS
    );
    println!(
        "packed_r_word0_depth={}",
        qfree_scheduler::QFREE_HASH_R_WORD0_DEPTH
    );
    println!("retained_r_suffix_items=0");
    println!("hash_helper_auxiliary_hint_items=0");
    println!("transition_auxiliary_hint_items_per_invocation=0");
    println!("transition_invocations=44");
    println!("challenge_recoder_auxiliary_hint_items=0");
    println!("additive_projected_policy_script_bytes={ADDITIVE_PROJECTED_LINKED_SCRIPT_BYTES}");
    println!("whole_leaf_metric_status=projection_pending_exact_generation");
    println!("caller_certifies_hash_source_words_via_final_derived_transition=true");
    println!("analytical_derived_combined_stack_peak={ANALYTICAL_DERIVED_COMBINED_STACK_PEAK}");
    println!("analytical_peak_phase=response");
    println!("analytical_peak_transition=1");
    println!("strict_synthetic_routing_peak={STRICT_SYNTHETIC_ROUTING_PEAK}");
    println!("run_explicit_measurement_with=--measure-bytes");
}

fn measure_bytes() {
    let linked = build_linked_leaf();
    let component_sum = linked.scalar_validator_bytes
        + linked.response_bytes
        + linked.hash_bytes
        + linked.recoder_bytes
        + linked.challenge_bytes
        + linked.terminal_bytes;
    assert_eq!(linked.whole.len(), component_sum);

    let compiled = linked.whole.compile_with_policy();
    assert!(compiled.len() > MAX_OPTIMIZER_INPUT_BYTES);
    // A leaf above the cutoff is deliberately serialized with no whole-script
    // optimizer pass.  Small components were policy-precompiled above.
    assert_eq!(compiled.len(), component_sum);
    assert_eq!(compiled.len(), ADDITIVE_PROJECTED_LINKED_SCRIPT_BYTES);
    let static_opcodes = static_non_push_opcodes(&compiled);

    println!("model=ed25519_montgomery_h16_qfree_full_linker");
    println!("mode=generation-only-byte-measurement");
    println!("evidence=locally-reproduced");
    println!("evidence_boundary=serialization");
    println!("execution_class=unclassified");
    println!("whole_leaf_execution_performed=false");
    println!("compile_options_for_whole_leaf=NONE");
    println!("whole_leaf_policy_bytes={}", compiled.len());
    println!("whole_leaf_static_non_push_opcodes={static_opcodes}");
    println!("linked_component_sum_bytes={component_sum}");
    println!("cross_component_optimizer_delta_bytes=0");
    println!("tables_bytes_included_in_schedules={}", linked.table_bytes);
    println!("qfree_non_table_raw_bytes={EXPECTED_QFREE_NON_TABLE_RAW_BYTES}");
    println!("derived_44_kernel_bytes={EXPECTED_DERIVED_KERNEL_BYTES}");
    println!("first_derived_kernel_bytes={EXPECTED_FIRST_DERIVED_KERNEL_BYTES}");
    println!("response_chained_derived_kernel_bytes={EXPECTED_RESPONSE_CHAINED_KERNEL_BYTES}");
    println!("challenge_chained_derived_kernel_bytes={EXPECTED_CHALLENGE_CHAINED_KERNEL_BYTES}");
    println!("response_scaffold_raw_bytes={EXPECTED_RESPONSE_SCAFFOLD_RAW_BYTES}");
    println!("challenge_scaffold_raw_bytes={EXPECTED_CHALLENGE_SCAFFOLD_RAW_BYTES}");
    println!(
        "scalar_validator_policy_bytes={}",
        linked.scalar_validator_bytes
    );
    println!("response_schedule_bytes={}", linked.response_bytes);
    println!("packed_r_direct_hash_policy_bytes={EXPECTED_PACKED_R_DIRECT_HASH_POLICY_BYTES}");
    println!("packed_r_conversion_policy_bytes={EXPECTED_PACKED_R_CONVERSION_POLICY_BYTES}");
    println!("packed_r_fixed_message_blake3_bytes={}", linked.hash_bytes);
    println!("packed_r_blake3_manual_post_policy_optimizer=false");
    println!(
        "independent_byte_recoder_policy_bytes={}",
        linked.recoder_bytes
    );
    println!("challenge_schedule_bytes={}", linked.challenge_bytes);
    println!("terminal_cleanstack_policy_bytes={}", linked.terminal_bytes);
    println!("auxiliary_hint_items={AUXILIARY_HINT_ITEMS}");
    println!(
        "complete_argument_items_at_script_entry={}",
        qfree_scheduler::QFREE_ENTRY_ITEMS
    );
    println!("analytical_derived_combined_stack_peak={ANALYTICAL_DERIVED_COMBINED_STACK_PEAK}");
    println!("analytical_peak_phase=response");
    println!("analytical_peak_transition=1");
    println!("strict_synthetic_routing_peak={STRICT_SYNTHETIC_ROUTING_PEAK}");
}

fn main() {
    match std::env::args().nth(1).as_deref() {
        None | Some("--check-shape") => check_shape(),
        Some("--measure-bytes") => measure_bytes(),
        Some(_) => panic!("use --check-shape or --measure-bytes"),
    }
}
